#include "main.h"


//蜂鸣器
#define BOARD_BUZZER_GPIO_PORT       BUZZER_CTRL_GPIO_Port
#define BOARD_BUZZER_GPIO_PIN        BUZZER_CTRL_Pin

#define BOARD_BUZZER_ACTIVE_LEVEL    GPIO_PIN_SET
#define BOARD_BUZZER_INACTIVE_LEVEL  GPIO_PIN_RESET

//运行指示灯
#define BOARD_LED_RUN_GPIO_PORT       RUN_LED_GPIO_Port
#define BOARD_LED_RUN_GPIO_PIN        RUN_LED_Pin

#define BOARD_LED_RUN_ACTIVE_LEVEL     GPIO_PIN_SET
#define BOARD_LED_RUN_INACTIVE_LEVEL   GPIO_PIN_RESET

//故障指示灯
#define BOARD_LED_FAULT_GPIO_PORT     FAULT_LED_GPIO_Port
#define BOARD_LED_FAULT_GPIO_PIN      FAULT_LED_Pin

#define BOARD_LED_FAULT_ACTIVE_LEVEL     GPIO_PIN_SET
#define BOARD_LED_FAULT_INACTIVE_LEVEL   GPIO_PIN_RESET



/*
*  继电器
*  引脚配置：PB12 -> RELAY_CTRL
*  有效电平：高电平有效
*/
#define BOARD_RELAY_GPIO_PORT         RELAY_CTRL_GPIO_Port
#define BOARD_RELAY_GPIO_PIN          RELAY_CTRL_Pin

#define BOARD_RELAY_ACTIVE_LEVEL      GPIO_PIN_SET
#define BOARD_RELAY_INACTIVE_LEVEL    GPIO_PIN_RESET



//按键








 


