#ifndef PROTOCOL_MQTT_TOPICS_H
#define PROTOCOL_MQTT_TOPICS_H

#include "NETWORK/network_config.h"

#define MQTT_UPLINK_STATUS_TOPIC  MQTT_TOPIC_STATUS
#define MQTT_UPLINK_ALARM_TOPIC   MQTT_TOPIC_ALARM
#define MQTT_UPLINK_ACK_TOPIC     MQTT_TOPIC_ACK
#define MQTT_DOWNLINK_COMMAND_TOPIC MQTT_TOPIC_COMMAND
#define MQTT_DOWNLINK_CONFIG_TOPIC  MQTT_TOPIC_CONFIG

#endif /* PROTOCOL_MQTT_TOPICS_H */
