//蜂鸣器
#define BOARD_BUZZER_GPIO_PORT       BUZZER_CTRL_GPIO_Port
#define BOARD_BUZZER_GPIO_PIN        BUZZER_CTRL_Pin

#define BOARD_BUZZER_ACTIVE_LEVEL    GPIO_PIN_SET
#define BOARD_BUZZER_INACTIVE_LEVEL  GPIO_PIN_RESET

//运行指示灯
#define BOARD_LED_RUN_GPIO_PORT       RUN_LED_GPIO_Port
#define BOARD_LED_RUN_GPIO_PIN        RUN_LED_Pin

#define BOARD_LED_RUN_ACTIVE_LEVEL     GPIO_PIN_SET
#define BOARD_LED_RUN_INACTIVE_LEVEL   GPIO_PIN_RESET

//故障指示灯
#define BOARD_LED_FAULT_GPIO_PORT     FAULT_LED_GPIO_Port
#define BOARD_LED_FAULT_GPIO_PIN      FAULT_LED_Pin

#define BOARD_LED_FAULT_ACTIVE_LEVEL     GPIO_PIN_SET
#define BOARD_LED_FAULT_INACTIVE_LEVEL   GPIO_PIN_RESET








